### ISSUE TITLE
Скукожило

### ISSUE THREAD

**Issue by T8RIN** [awxkee/jxl-coder#10]
![Screenshot_20240107-200459.png](https://github.com/awxkee/jxl-coder/assets/52178347/92f6cef4-c82c-407b-83ba-d30c6dbfda9b)

А что с jxl кодером стало (справа его работа), почему так кукожить он начал... Раньше точно все норм было, с какой версии это пошло не знаю, но сейчас стоит 1.5.7

**Comment by awxkee** [comment]
Какие это настройки? Я переделывал как-то уровни кач-ва, скорее всего твои настройки качества где-то не сходятся с новыми

**Comment by T8RIN** [comment]
![image](https://github.com/awxkee/jxl-coder/assets/52178347/9c007f59-e211-4d9b-a2e2-1cbd24af9d09)

**Comment by T8RIN** [comment]
на 1.5.5 так же чет

**Comment by awxkee** [comment]
Дай картинки которые жмешь, я не видел такого, может в картинке дело

**Comment by T8RIN** [comment]
![Screenshot_20240107-191800.png](https://github.com/awxkee/jxl-coder/assets/52178347/0d996df5-21f9-48cb-9cd3-4ae03afbe64a)

**Comment by T8RIN** [comment]
может в декодинге проблема?

![image](https://github.com/awxkee/jxl-coder/assets/52178347/feabe380-3bdc-41cb-9d43-656186280d8e)

**Comment by T8RIN** [comment]
Этот катмул ром не может так корявить?

**Comment by awxkee** [comment]
Я тут обновляю как раз jxl-coder, и там вообще в скейле был маленький баг, может из-за него

**Comment by T8RIN** [comment]
Возможно вполне, это ж мне скейлер тож надо будет обновить?

**Comment by awxkee** [comment]
Да, я посмотрю и скажу точно что это

**Comment by T8RIN** [comment]
Окей, спасибо :)

**Comment by awxkee** [comment]
> Возможно вполне, это ж мне скейлер тож надо будет обновить?

Я посмотрел скейл, пофикшенный, после его применения на уменьшении картинки деградация примерно совпадает с андроидовским, может ты просто не применяешь правильно скейл в варианте не JXL? ( и еще Catmull Rom и все кубические сплайны сами по себе плохо работают на уменьшение )

Картинка сжатая моим скейлем с Catmull Rom в 3 раза,

![Screenshot_20240107_174100_JXLCoder](https://github.com/awxkee/jxl-coder/assets/17083179/e62121ff-b88d-465b-86bc-9103edab7285)

Картинка сжатая андроид скейлом в 3 раза,
![Screenshot_20240107_174217_JXLCoder](https://github.com/awxkee/jxl-coder/assets/17083179/462aff90-749d-4ce9-98a4-72486339e94b)

Как по мне так Catmull Rom даже лучше справился

**Comment by T8RIN** [comment]
Не , к скейлеру вопросов нет вроде, а вот jxl странно делает...

**Comment by awxkee** [comment]
Я посмотрел кстати твой коммит, ты там путаешь, BSpline у меня был это бикубический сплайн, а Cubic - это обычные кубические сплайны

**Comment by awxkee** [comment]
> Не , к скейлеру вопросов нет вроде, а вот jxl странно делает...

вот 2 изображения выше, одно я сжал в 3 раза JXL, 2 я сжал в 3 раза андроидом, я не вижу особой разницы

**Comment by T8RIN** [comment]
> Я посмотрел кстати твой коммит, ты там путаешь, BSpline у меня был это бикубический сплайн, а Cubic - это обычные кубические сплайны

А, поменяю тогда местами

**Comment by T8RIN** [comment]
> > Не , к скейлеру вопросов нет вроде, а вот jxl странно делает...
> 
> вот 2 изображения выше, одно я сжал в 3 раза JXL, 2 я сжал в 3 раза андроидом, я не вижу особой разницы

Хм, вроде все норм я там показываю, щас загружу конвертнутый, я там даже не меняю размер а оно корявит

**Comment by T8RIN** [comment]
![Screenshot_20240107-204909.png](https://github.com/awxkee/jxl-coder/assets/52178347/a7b341dc-055d-49a5-a78e-bb3a6ab39714)

**Comment by T8RIN** [comment]
![ResizedImage_2024-01-07_20-51-01_1916.jpg](https://github.com/awxkee/jxl-coder/assets/52178347/64c7e408-2087-4fe4-aaae-85423c1c5f1d)

Этот jxl ни вставить ни выбрать нормально, поддержка околонулевая в системе, вот переименовал в jpg

**Comment by T8RIN** [comment]
Получилось по ссылке его открыть, ![Screenshot_20240107-205555.png](https://github.com/awxkee/jxl-coder/assets/52178347/43baa38b-1d91-4841-8e24-eceb5b970783)

Тут никаких косяков не видно, может в декодере реально проблема

**Comment by awxkee** [comment]
Глянь какие у тебя dstWidth. + dstHeight передаются в декодер

**Comment by awxkee** [comment]
Понятно, он скорее всего очень маленькие размеры я думаю все же передает, ты можешь брейкпоит прямо внутри `decodeSampled` поставить и посмотреть там?

**Comment by T8RIN** [comment]
Щас попробую

**Comment by T8RIN** [comment]
![image](https://github.com/awxkee/jxl-coder/assets/52178347/5229e236-7f2f-48a1-a854-618eb609f51d)

**Comment by T8RIN** [comment]
![Screenshot_20240107-211507.png](https://github.com/awxkee/jxl-coder/assets/52178347/00474862-df78-4cb0-8349-dec9dabe28f1)

Он с любой картинкой это вытворяет

![ResizedImage_2024-01-07_21-09-21_2030.png](https://github.com/awxkee/jxl-coder/assets/52178347/8260c427-be65-47d4-8500-8bcca9f70f6c)

**Comment by T8RIN** [comment]
Так, ну хотя не с каждой, ток при уменьшении

**Comment by T8RIN** [comment]
Но странно, в авифе ж все норм

**Comment by awxkee** [comment]
> Так, ну хотя не с каждой, ток при уменьшении

Там был небольшой баг с кубическими фильтрами, и да, катмул ром не очень хорош, бикубический сплайн лучше результат выдает

**Comment by awxkee** [comment]
> > Так, ну хотя не с каждой, ток при уменьшении
> 
> Там был небольшой баг с кубическими фильтрами, и да, катмул ром не очень хорош, бикубический сплайн лучше результат выдает

в авиф билинейный скейл из libheif, я тут видимо забыл катмул ром убрать, не помню зачем я его поставил, но видимо сейчас тоже будет билинейный по дефолту и тут

**Comment by T8RIN** [comment]
Окей, а фиксы в XScaler'е будут?

**Comment by awxkee** [comment]
> Окей, а фиксы в XScaler'е будут?

Да

**Comment by T8RIN** [comment]
![image](https://github.com/awxkee/jxl-coder/assets/52178347/88a29a4e-768c-46d8-b29f-80a4e56de296)
ааэаэ

**Comment by awxkee** [comment]
оно работает скопируй все правильно )

**Comment by T8RIN** [comment]
буковка к буковке скопировал

**Comment by T8RIN** [comment]
![image](https://github.com/awxkee/jxl-coder/assets/52178347/57744c2b-b940-40a7-a6dd-47eb39ccfbfd)

**Comment by T8RIN** [comment]
ааа, походу либы еще надо скопировать по новой

**Comment by awxkee** [comment]
да, hwy я обновил с libjxl

**Comment by awxkee** [comment]
1.6.0 версии попробуй как там со скейлом будет, я просмотрел кучу вариантов, вроде аномалий быть не должно

**Comment by T8RIN** [comment]
Окей

**Comment by T8RIN** [comment]
![image](https://github.com/awxkee/jxl-coder/assets/52178347/463d90b5-5144-4dd2-bae2-411b33c66b51)

теперь ваще не работает

**Comment by awxkee** [comment]
Хм, это та же картинка?

**Comment by T8RIN** [comment]
ваще на любой падает

**Comment by T8RIN** [comment]
![image](https://github.com/awxkee/jxl-coder/assets/52178347/5d44e48d-e7c3-419a-af21-3d18160f05bb)

**Comment by T8RIN** [comment]
а скейлер работает норм, ток джксл пытаюсь сделать сразу креш через секунду

**Comment by awxkee** [comment]
Ок, буду смотреть, видимо что-то пошло не так

**Comment by T8RIN** [comment]
Буду ждать :)

**Comment by awxkee** [comment]
А билинейный скейл правилньо работает на твоем телефоне? Запусти на несольких картинках сразу

**Comment by T8RIN** [comment]
Опа, вылетает

**Comment by T8RIN** [comment]
А ты кста не можешь там try catch поставить, чтобы если падало, то java exception выбрасывала, нативные я ловить не могу, чтобы прога не падала, а прост креш активити показывалась

**Comment by awxkee** [comment]
Дай плз картинку



> А ты кста не можешь там try catch поставить, чтобы если падало, то java exception выбрасывала, нативные я ловить не могу, чтобы прога не падала, а прост креш активити показывалась

На те исключеия что есть, try catch добавлен, на такое нельзя

**Comment by T8RIN** [comment]
Падает в общем на любой картинке, если билинейно увеличивать, но вот пример 

![_.__2023-12-06_19-26-48_3367.png](https://github.com/awxkee/jxl-coder/assets/52178347/84bd0d78-685c-4d7b-9c8a-e5db1653507e)

**Comment by awxkee** [comment]
Попробуй XScaler который я только что отправил-  если не сработает тогда я удалю то что крешит точно

**Comment by T8RIN** [comment]
Ща

**Comment by T8RIN** [comment]
Вылетает

**Comment by T8RIN** [comment]
![image](https://github.com/awxkee/jxl-coder/assets/52178347/dfa00f8b-6894-44cf-bf46-be92ebdf9b79)

**Comment by T8RIN** [comment]
походу в jxl тоже поэтому вылетает

**Comment by awxkee** [comment]
Понятно, спасибо. Да, это один и тот же баг, хотел как лучше  - получилось как всегда )

**Comment by T8RIN** [comment]
Хе, да ничего, жду фикса :)

**Comment by awxkee** [comment]
Готово, в 1.6.1

**Comment by T8RIN** [comment]
Ура, заработало, спасибо :)

**Comment by awxkee** [comment]
> Ура, заработало, спасибо :)

Можешь еще раз скейлер взять, мне тут его еще подускорить было нужно)

**Comment by T8RIN** [comment]
О! Спасибо еще раз :)
