### ISSUE TITLE
libskcms

### ISSUE THREAD

**Issue by T8RIN** [awxkee/jxl-coder#11]
А эт для чего кстати?👀

**Comment by awxkee** [comment]
Последняя версия libjxl перешла стала видимо использовать skia для цветовых пространств, у меня на иос без нее некоторые сборки не собирались, я решил вставить на всякий случай так как мне не хочеться разбираться нужна она или нет на андроиде. Разницы особо ты не должен видеть если она не нужна линкер ее удалит)

**Comment by T8RIN** [comment]
А, окей, спасибо :)

**Comment by T8RIN** [comment]
Привет снова, а у тебя есть телеграм? Тут чето с режимами увеличение странное происходит

Вот мой, если есть @T8RIN
