### ISSUE TITLE
JXL lossless JPEG transcoding

### ISSUE THREAD

**Issue by kremzli** [awxkee/jxl-coder#12]
One of JXL's main features is lossless and reversible JPEG transcoding, completely losslessly converting optimised JPEG is many times only going to be bigger, and take a bit longer.

I suggest adding lossless JPEG transcoding. Maybe add a function to reverse it too.

**Comment by awxkee** [comment]
Yes. And for now as android do not support JXL in full and only one use case to use JXL is receive images from your own server and sometimes send to it what's the reason to implement this feature?

**Comment by awxkee** [comment]
If it's important especially for you then I'm glad to accept PR

**Comment by kremzli** [comment]
JXL is quite clearly popular with pros (photographers, or other media stuff) and web devs (https://github.com/web-platform-tests/interop/issues/430), and this feature is very important for "converting" (transcoding) lots of files (fully converting optimised jpeg usually isnt good), and reversing that is useful for compatibility with things that are not maintained anymore or get slow updates. JXL will inevitably be supported as the next JPG, and this is a main feature of JXL, so this library is probably going to need this feature later anyway?

**Comment by awxkee** [comment]
I think the photographer software will implement this feature without my library as well the JXL in full. Sure, If there are some signs that situation with Google and JXL will improve the feature in library highly likely will be done. For now when it's almost impossible to use JXL outside the app it's not really clear to me why implementing and maintaining this feature worth it

**Comment by awxkee** [comment]
Reconstruction API available since 2.0.0 version
