### ISSUE TITLE
Clarification on supported Android versions

### ISSUE THREAD

**Issue by antermin** [awxkee/jxl-coder#13]
Regarding "for Android 21+" in README, does that mean...
* Android 14 (according to [Wikipedia](https://en.wikipedia.org/wiki/Android_14), it is the 21st version of Android)?
* Android 5.0 (API Level 21)?
* Android 12+? (A typo in README?)
* Something else?

**Comment by awxkee** [comment]
Thank for the suggestion I'll change to 'Android 5.0 (API Level 21)' in the README. Usually in android development we track only API level
