### ISSUE TITLE
Clarification for speed setting.

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [awxkee/jxl-coder#14]
In JPEG XL, there is effort setting where 10 is the slowest.

For the speed setting, what is the value supposed to mean?

**Comment by awxkee** [comment]
The effort and speed are two different parameters. As my best knowledge Jxl can be encoded in different ways for increasing/decreasing decoding speed of Jxl image. The parameter is responsible for that. If you would like to know more better refer to libjxl documentation

**Comment by Ahmad-Amsyar** [comment]
> The effort and speed are two different parameters. As my best knowledge Jxl can be encoded in different ways for increasing/decreasing decoding speed of Jxl image. The parameter is responsible for that. If you would like to know more better refer to libjxl documentation 

Understood, thank you for the explanation.
