### ISSUE TITLE
Wrong color decoding

### ISSUE THREAD

**Issue by kremzli** [awxkee/jxl-coder#16]
Just this:
https://github.com/T8RIN/ImageToolbox/issues/893#issuecomment-2007944732

Its still the same with 2.1.8

**Comment by awxkee** [comment]
I have a few questions because the default sRGB are doing well as I see.

Does your picture have alpha?
Does your picture contains embedded ICC or NCLX profile?
What android API version is used?
May you provide original image or a few?

**Comment by kremzli** [comment]
Quite sure all the images have nothing special (they are all from Discord), im on Android 14 (OneUI 6.0)
Heres a link to the converted JXL's and the source images: https://drive.proton.me/urls/F9XCTGDXZM#oiYgeqLBFjaI

They decode as expected on KDE's image viewer Gwenview (Linux)

**Comment by awxkee** [comment]
One image is sRGB, other one contains Display P3 sRGB Transfer ICC profile, however I don't see any difference in test app after roundtrip with encoding and decoding

![Screenshot_20240328_153905_JXLCoder](https://github.com/awxkee/jxl-coder/assets/17083179/200098d6-8107-419b-aabf-7fd433dca0bf)

![Screenshot_20240328_153900_JXLCoder](https://github.com/awxkee/jxl-coder/assets/17083179/483a4831-a08d-4f18-b70d-5abe6e09f538)

**Comment by awxkee** [comment]
Did I miss something?

**Comment by awxkee** [comment]
I'm not able to reproduce in test app on my side any of those wrong conversion.
