### ISSUE TITLE
Alpha support 

### ISSUE THREAD

**Issue by T8RIN** [awxkee/jxl-coder#2]
Please add alpha support if it is possible 🙏

**Comment by awxkee** [comment]
> Please add alpha support if it is possible 🙏

I've added alpha encoding, but one of reason of JXL is re - compress old JPEG files into JXL, and this flow makes unreasonable added alpha channel

**Comment by T8RIN** [comment]
> > Please add alpha support if it is possible 🙏
> 
> I've added alpha encoding, but one of reason of JXL is re - compress old JPEG files into JXL, and this flow makes unreasonable added alpha channel

That's more for example converting png into jxl with saving alpha channel
