### ISSUE TITLE
Dart/Flutter package

### ISSUE THREAD

**Issue by stephane-archer** [awxkee/jxl-coder#21]
Hi, thank you for making this awesome package.
As mentioned here, I used jxl-coder-swift in one of my app and made a Dart packge: https://github.com/awxkee/jxl-coder-swift/issues/5
I think it would be awesome if we could add Android support using this package
You might want to have a look: https://github.com/stephane-archer/flutter-jxl-coder

Thanks again for making this package

**Comment by awxkee** [comment]
Hi,

Looks nice!
My knoweldge of flutter a little limited by launching **Hello World** somewhere in ~2017, but sure, you can use this repo for your project.
