### ISSUE TITLE
Request: please put license for the repository

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [awxkee/jxl-coder#5]
Apache/MIT could be nice.

**Comment by AndroidDeveloperLB** [comment]
Wait, this means that any person that wishes to use it inside the app, it has to be open sourced and have the same license too?

**Comment by awxkee** [comment]
No, BSD allows to use this in commercial software, but yes, the copy of license is required in project

**Comment by AndroidDeveloperLB** [comment]
By "copy of license is required in project", you mean that I should have some credit in the UI to show the user that the app uses this library, and a mention of the license there?
Or something else?

**Comment by awxkee** [comment]
Yes, you have to mention the product, authors, and license. 

`libjxl` distributed under this license so I can't change it to another

**Comment by awxkee** [comment]
Finally, I think it's ok. Project will be `MIT` with mention about `libjxl`

**Comment by AndroidDeveloperLB** [comment]
I don't understand. You talked with them and they agreed it's fine?

**Comment by awxkee** [comment]
Yes, it's ok

**Comment by AndroidDeveloperLB** [comment]
Thank you very much!
