### ISSUE TITLE
Jitpack Issue

### ISSUE THREAD

**Issue by T8RIN** [awxkee/jxl-coder#8]
Could not GET 'https://jitpack.io/com/github/awxkee/jxlcoder/1.2.3/jxlcoder-1.2.3.pom'. Received status code 401 from server: Unauthorized ;(

**Comment by awxkee** [comment]
> Could not GET 'https://jitpack.io/com/github/awxkee/jxlcoder/1.2.3/jxlcoder-1.2.3.pom'. Received status code 401 from server: Unauthorized ;(

Sorry there is a typo, it should be `com.github.awxkee:jxl-coder:1.2.3`

**Comment by T8RIN** [comment]
Oh, thanks :)
