### ISSUE TITLE
Checking is JXL

### ISSUE THREAD

**Issue by T8RIN** [awxkee/jxl-coder#9]
By some reason this checking doesn't work, what can i do?

``` kotlin

private val MAGIC_1 = byteArrayOf(0xFF.toByte(), 0x0A).toByteString()
        private val MAGIC_2 = byteArrayOf(
            0x0.toByte(),
            0x0.toByte(),
            0x0.toByte(),
            0x0C.toByte(),
            0x4A,
            0x58,
            0x4C,
            0x20,
            0x0D,
            0x0A,
            0x87.toByte(),
            0x0A
        ).toByteString()

        private fun isJXL(source: BufferedSource): Boolean {
            return source.rangeEquals(2, MAGIC_1) || source.rangeEquals(
                MAGIC_2.size.toLong(),
                MAGIC_2
            )
        }

```

i'm using coil written JxlDecoder

here is full code
``` kotlin

class JxlDecoder(
    private val source: SourceResult,
    private val options: Options,
    private val imageLoader: ImageLoader
) : Decoder {

    override suspend fun decode(): DecodeResult? = runInterruptible {
        val byteArray = source.source.source().readByteArray()
        val originalSize = JxlCoder().getSize(byteArray) ?: return@runInterruptible null
        val dstWidth = options.size.width.pxOrElse { 0 }
        val dstHeight = options.size.height.pxOrElse { 0 }
        if (options.scale == Scale.FIT) {
            val scaledSize = aspectScale(originalSize, Size(dstWidth, dstHeight))
            val originalImage =
                JxlCoder().decodeSampled(byteArray, scaledSize.width, scaledSize.height)
            return@runInterruptible DecodeResult(
                BitmapDrawable(
                    options.context.resources,
                    originalImage
                ), true
            )
        }
        val originalImage = JxlCoder().decode(byteArray)
        val resizedBitmap = resizeAspectFill(originalImage, Size(dstWidth, dstHeight))
        originalImage.recycle()
        return@runInterruptible DecodeResult(
            BitmapDrawable(
                options.context.resources,
                resizedBitmap
            ), true
        )
    }

    private fun resizeAspectFill(sourceBitmap: Bitmap, dstSize: Size): Bitmap {
        val background = Bitmap.createBitmap(dstSize.width, dstSize.height, Bitmap.Config.ARGB_8888)
        val originalWidth: Float = background.width.toFloat()
        val originalHeight: Float = background.height.toFloat()
        val canvas = Canvas(background)

        val scale: Float =
            if (dstSize.height > dstSize.width) dstSize.height / originalHeight else dstSize.width / originalWidth

        val xTranslation = (dstSize.width - originalWidth * scale) / 2.0f
        val yTranslation: Float = (dstSize.height - originalHeight * scale) / 2.0f

        val transformation = Matrix()
        transformation.postTranslate(xTranslation, yTranslation)
        transformation.preScale(scale, scale)

        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        paint.isFilterBitmap = true

        canvas.drawBitmap(sourceBitmap, transformation, paint)
        return background
    }

    private fun aspectScale(sourceSize: Size, dstSize: Size): Size {
        val isHorizontal = sourceSize.width > sourceSize.height
        val targetSize = if (isHorizontal) dstSize else Size(dstSize.height, dstSize.width)
        if (targetSize.width > sourceSize.width && targetSize.height > sourceSize.height) {
            return sourceSize
        }
        val imageAspectRatio = sourceSize.width.toFloat() / sourceSize.height.toFloat()
        val canvasAspectRation = targetSize.width.toFloat() / targetSize.height.toFloat()
        val resizeFactor: Float = if (imageAspectRatio > canvasAspectRation) {
            targetSize.width.toFloat() / sourceSize.width.toFloat()
        } else {
            targetSize.height.toFloat() / sourceSize.height.toFloat()
        }
        return Size(
            (sourceSize.width.toFloat() * resizeFactor).toInt(),
            (sourceSize.height.toFloat() * resizeFactor).toInt()
        )
    }

    class Factory : Decoder.Factory {
        override fun create(
            result: SourceResult,
            options: Options,
            imageLoader: ImageLoader
        ) = if (isJXL(result.source.source())) {
            JxlDecoder(result, options, imageLoader)
        } else null

        private val MAGIC_1 = byteArrayOf(0xFF.toByte(), 0x0A).toByteString()
        private val MAGIC_2 = byteArrayOf(
            0x0.toByte(),
            0x0.toByte(),
            0x0.toByte(),
            0x0C.toByte(),
            0x4A,
            0x58,
            0x4C,
            0x20,
            0x0D,
            0x0A,
            0x87.toByte(),
            0x0A
        ).toByteString()

        private fun isJXL(source: BufferedSource): Boolean {
            return source.rangeEquals(2, MAGIC_1) || source.rangeEquals(
                MAGIC_2.size.toLong(),
                MAGIC_2
            )
        }
    }

}

```

**Comment by awxkee** [comment]
> By some reason this checking doesn't work, what can i do?
> 
> ```kotlin
> private val MAGIC_1 = byteArrayOf(0xFF.toByte(), 0x0A).toByteString()
>         private val MAGIC_2 = byteArrayOf(
>             0x0.toByte(),
>             0x0.toByte(),
>             0x0.toByte(),
>             0x0C.toByte(),
>             0x4A,
>             0x58,
>             0x4C,
>             0x20,
>             0x0D,
>             0x0A,
>             0x87.toByte(),
>             0x0A
>         ).toByteString()
> 
>         private fun isJXL(source: BufferedSource): Boolean {
>             return source.rangeEquals(2, MAGIC_1) || source.rangeEquals(
>                 MAGIC_2.size.toLong(),
>                 MAGIC_2
>             )
>         }
> ```
> 
> i'm using coil written JxlDecoder
> 
> here is full code
> 
> ```kotlin
> class JxlDecoder(
>     private val source: SourceResult,
>     private val options: Options,
>     private val imageLoader: ImageLoader
> ) : Decoder {
> 
>     override suspend fun decode(): DecodeResult? = runInterruptible {
>         val byteArray = source.source.source().readByteArray()
>         val originalSize = JxlCoder().getSize(byteArray) ?: return@runInterruptible null
>         val dstWidth = options.size.width.pxOrElse { 0 }
>         val dstHeight = options.size.height.pxOrElse { 0 }
>         if (options.scale == Scale.FIT) {
>             val scaledSize = aspectScale(originalSize, Size(dstWidth, dstHeight))
>             val originalImage =
>                 JxlCoder().decodeSampled(byteArray, scaledSize.width, scaledSize.height)
>             return@runInterruptible DecodeResult(
>                 BitmapDrawable(
>                     options.context.resources,
>                     originalImage
>                 ), true
>             )
>         }
>         val originalImage = JxlCoder().decode(byteArray)
>         val resizedBitmap = resizeAspectFill(originalImage, Size(dstWidth, dstHeight))
>         originalImage.recycle()
>         return@runInterruptible DecodeResult(
>             BitmapDrawable(
>                 options.context.resources,
>                 resizedBitmap
>             ), true
>         )
>     }
> 
>     private fun resizeAspectFill(sourceBitmap: Bitmap, dstSize: Size): Bitmap {
>         val background = Bitmap.createBitmap(dstSize.width, dstSize.height, Bitmap.Config.ARGB_8888)
>         val originalWidth: Float = background.width.toFloat()
>         val originalHeight: Float = background.height.toFloat()
>         val canvas = Canvas(background)
> 
>         val scale: Float =
>             if (dstSize.height > dstSize.width) dstSize.height / originalHeight else dstSize.width / originalWidth
> 
>         val xTranslation = (dstSize.width - originalWidth * scale) / 2.0f
>         val yTranslation: Float = (dstSize.height - originalHeight * scale) / 2.0f
> 
>         val transformation = Matrix()
>         transformation.postTranslate(xTranslation, yTranslation)
>         transformation.preScale(scale, scale)
> 
>         val paint = Paint(Paint.ANTI_ALIAS_FLAG)
>         paint.isFilterBitmap = true
> 
>         canvas.drawBitmap(sourceBitmap, transformation, paint)
>         return background
>     }
> 
>     private fun aspectScale(sourceSize: Size, dstSize: Size): Size {
>         val isHorizontal = sourceSize.width > sourceSize.height
>         val targetSize = if (isHorizontal) dstSize else Size(dstSize.height, dstSize.width)
>         if (targetSize.width > sourceSize.width && targetSize.height > sourceSize.height) {
>             return sourceSize
>         }
>         val imageAspectRatio = sourceSize.width.toFloat() / sourceSize.height.toFloat()
>         val canvasAspectRation = targetSize.width.toFloat() / targetSize.height.toFloat()
>         val resizeFactor: Float = if (imageAspectRatio > canvasAspectRation) {
>             targetSize.width.toFloat() / sourceSize.width.toFloat()
>         } else {
>             targetSize.height.toFloat() / sourceSize.height.toFloat()
>         }
>         return Size(
>             (sourceSize.width.toFloat() * resizeFactor).toInt(),
>             (sourceSize.height.toFloat() * resizeFactor).toInt()
>         )
>     }
> 
>     class Factory : Decoder.Factory {
>         override fun create(
>             result: SourceResult,
>             options: Options,
>             imageLoader: ImageLoader
>         ) = if (isJXL(result.source.source())) {
>             JxlDecoder(result, options, imageLoader)
>         } else null
> 
>         private val MAGIC_1 = byteArrayOf(0xFF.toByte(), 0x0A).toByteString()
>         private val MAGIC_2 = byteArrayOf(
>             0x0.toByte(),
>             0x0.toByte(),
>             0x0.toByte(),
>             0x0C.toByte(),
>             0x4A,
>             0x58,
>             0x4C,
>             0x20,
>             0x0D,
>             0x0A,
>             0x87.toByte(),
>             0x0A
>         ).toByteString()
> 
>         private fun isJXL(source: BufferedSource): Boolean {
>             return source.rangeEquals(2, MAGIC_1) || source.rangeEquals(
>                 MAGIC_2.size.toLong(),
>                 MAGIC_2
>             )
>         }
>     }
> 
> }
> ```

You need this one. `https://github.com/awxkee/jxl-coder/blob/master/app/src/main/java/com/awxkee/jxlcoder/JxlDecoder.kt`. 
It doesn't work because you chose invalid offset to check magic

**Comment by T8RIN** [comment]
> > By some reason this checking doesn't work, what can i do?
> > 
> > ```kotlin
> > private val MAGIC_1 = byteArrayOf(0xFF.toByte(), 0x0A).toByteString()
> >         private val MAGIC_2 = byteArrayOf(
> >             0x0.toByte(),
> >             0x0.toByte(),
> >             0x0.toByte(),
> >             0x0C.toByte(),
> >             0x4A,
> >             0x58,
> >             0x4C,
> >             0x20,
> >             0x0D,
> >             0x0A,
> >             0x87.toByte(),
> >             0x0A
> >         ).toByteString()
> > 
> >         private fun isJXL(source: BufferedSource): Boolean {
> >             return source.rangeEquals(2, MAGIC_1) || source.rangeEquals(
> >                 MAGIC_2.size.toLong(),
> >                 MAGIC_2
> >             )
> >         }
> > ```
> > 
> > i'm using coil written JxlDecoder
> > 
> > here is full code
> > 
> > ```kotlin
> > class JxlDecoder(
> >     private val source: SourceResult,
> >     private val options: Options,
> >     private val imageLoader: ImageLoader
> > ) : Decoder {
> > 
> >     override suspend fun decode(): DecodeResult? = runInterruptible {
> >         val byteArray = source.source.source().readByteArray()
> >         val originalSize = JxlCoder().getSize(byteArray) ?: return@runInterruptible null
> >         val dstWidth = options.size.width.pxOrElse { 0 }
> >         val dstHeight = options.size.height.pxOrElse { 0 }
> >         if (options.scale == Scale.FIT) {
> >             val scaledSize = aspectScale(originalSize, Size(dstWidth, dstHeight))
> >             val originalImage =
> >                 JxlCoder().decodeSampled(byteArray, scaledSize.width, scaledSize.height)
> >             return@runInterruptible DecodeResult(
> >                 BitmapDrawable(
> >                     options.context.resources,
> >                     originalImage
> >                 ), true
> >             )
> >         }
> >         val originalImage = JxlCoder().decode(byteArray)
> >         val resizedBitmap = resizeAspectFill(originalImage, Size(dstWidth, dstHeight))
> >         originalImage.recycle()
> >         return@runInterruptible DecodeResult(
> >             BitmapDrawable(
> >                 options.context.resources,
> >                 resizedBitmap
> >             ), true
> >         )
> >     }
> > 
> >     private fun resizeAspectFill(sourceBitmap: Bitmap, dstSize: Size): Bitmap {
> >         val background = Bitmap.createBitmap(dstSize.width, dstSize.height, Bitmap.Config.ARGB_8888)
> >         val originalWidth: Float = background.width.toFloat()
> >         val originalHeight: Float = background.height.toFloat()
> >         val canvas = Canvas(background)
> > 
> >         val scale: Float =
> >             if (dstSize.height > dstSize.width) dstSize.height / originalHeight else dstSize.width / originalWidth
> > 
> >         val xTranslation = (dstSize.width - originalWidth * scale) / 2.0f
> >         val yTranslation: Float = (dstSize.height - originalHeight * scale) / 2.0f
> > 
> >         val transformation = Matrix()
> >         transformation.postTranslate(xTranslation, yTranslation)
> >         transformation.preScale(scale, scale)
> > 
> >         val paint = Paint(Paint.ANTI_ALIAS_FLAG)
> >         paint.isFilterBitmap = true
> > 
> >         canvas.drawBitmap(sourceBitmap, transformation, paint)
> >         return background
> >     }
> > 
> >     private fun aspectScale(sourceSize: Size, dstSize: Size): Size {
> >         val isHorizontal = sourceSize.width > sourceSize.height
> >         val targetSize = if (isHorizontal) dstSize else Size(dstSize.height, dstSize.width)
> >         if (targetSize.width > sourceSize.width && targetSize.height > sourceSize.height) {
> >             return sourceSize
> >         }
> >         val imageAspectRatio = sourceSize.width.toFloat() / sourceSize.height.toFloat()
> >         val canvasAspectRation = targetSize.width.toFloat() / targetSize.height.toFloat()
> >         val resizeFactor: Float = if (imageAspectRatio > canvasAspectRation) {
> >             targetSize.width.toFloat() / sourceSize.width.toFloat()
> >         } else {
> >             targetSize.height.toFloat() / sourceSize.height.toFloat()
> >         }
> >         return Size(
> >             (sourceSize.width.toFloat() * resizeFactor).toInt(),
> >             (sourceSize.height.toFloat() * resizeFactor).toInt()
> >         )
> >     }
> > 
> >     class Factory : Decoder.Factory {
> >         override fun create(
> >             result: SourceResult,
> >             options: Options,
> >             imageLoader: ImageLoader
> >         ) = if (isJXL(result.source.source())) {
> >             JxlDecoder(result, options, imageLoader)
> >         } else null
> > 
> >         private val MAGIC_1 = byteArrayOf(0xFF.toByte(), 0x0A).toByteString()
> >         private val MAGIC_2 = byteArrayOf(
> >             0x0.toByte(),
> >             0x0.toByte(),
> >             0x0.toByte(),
> >             0x0C.toByte(),
> >             0x4A,
> >             0x58,
> >             0x4C,
> >             0x20,
> >             0x0D,
> >             0x0A,
> >             0x87.toByte(),
> >             0x0A
> >         ).toByteString()
> > 
> >         private fun isJXL(source: BufferedSource): Boolean {
> >             return source.rangeEquals(2, MAGIC_1) || source.rangeEquals(
> >                 MAGIC_2.size.toLong(),
> >                 MAGIC_2
> >             )
> >         }
> >     }
> > 
> > }
> > ```
> 
> You need this one. `https://github.com/awxkee/jxl-coder/blob/master/app/src/main/java/com/awxkee/jxlcoder/JxlDecoder.kt`. 
> It doesn't work because you chose invalid offset to check magic

Oh, thanks!

**Comment by awxkee** [comment]
I also added a proper effort option value to encode JXL in '1.3.0'

**Comment by T8RIN** [comment]
> I also added a proper effort option value to encode JXL in '1.3.0'

You mean quality?

**Comment by awxkee** [comment]
> > I also added a proper effort option value to encode JXL in '1.3.0'
> 
> You mean quality?

It mean effort on compression, but effort will affect quality

**Comment by awxkee** [comment]
> By some reason 1.3.0 crashes with this
> 
> [Bug] App Crash: JXLCoderCompressionException
> 
> Device: Mi 9T Pro (Xiaomi - raphael), SDK: 33 (13), App: 2.3.2-jxl (86)
> 
> com.awxkee.jxlcoder.JXLCoderCompressionException: at com.awxkee.jxlcoder.JxlCoder.encodeImpl(Native Method) at com.awxkee.jxlcoder.JxlCoder.encode(JxlCoder.kt:48) at ru.tech.imageresizershrinker.data.image.ImageCompressor.compress(ImageCompressor.kt:116) at ru.tech.imageresizershrinker.data.image.AndroidImageManager$compress$2.invokeSuspend(AndroidImageManager.kt:609) at ru.tech.imageresizershrinker.data.image.AndroidImageManager$compress$2.invoke(Unknown Source:8) at ru.tech.imageresizershrinker.data.image.AndroidImageManager$compress$2.invoke(Unknown Source:4) at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78) at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167) at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) at ru.tech.imageresizershrinker.data.image.AndroidImageManager.compress(AndroidImageManager.kt:590) at ru.tech.imageresizershrinker.domain.image.ImageManager$DefaultImpls.compress$default(ImageManager.kt:46) at ru.tech.imageresizershrinker.data.image.AndroidImageManager$createPreview$2.invokeSuspend(AndroidImageManager.kt:643) at ru.tech.imageresizershrinker.data.image.AndroidImageManager$createPreview$2.invoke(Unknown Source:8) at ru.tech.imageresizershrinker.data.image.AndroidImageManager$createPreview$2.invoke(Unknown Source:4) at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78) at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167) at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) at ru.tech.imageresizershrinker.data.image.AndroidImageManager.createPreview(AndroidImageManager.kt:632) at ru.tech.imageresizershrinker.data.image.AndroidImageManager.createPreview(AndroidImageManager.kt:43) at ru.tech.imageresizershrinker.presentation.single_edit_screen.viewModel.SingleEditViewModel$updatePreview$2.invokeSuspend(SingleEditViewModel.kt:173) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115) at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@21f5372, Dispatchers.Main.immediate]

I can't reproduce this, can you give me an image and parameters that you used to compress?

**Comment by T8RIN** [comment]
Source code here -> [link](https://github.com/T8RIN/ImageToolbox/blob/master/app/src/jxl/java/ru/tech/imageresizershrinker/data/image/ImageCompressor.kt)

apk here -> 
[image-toolbox-2.3.2-jxl-arm64-v8a-release.zip](https://github.com/awxkee/jxl-coder/files/12545944/image-toolbox-2.3.2-jxl-arm64-v8a-release.zip)


fails with every image...

**Comment by awxkee** [comment]
> Source code here -> [link](https://github.com/T8RIN/ImageToolbox/blob/master/app/src/jxl/java/ru/tech/imageresizershrinker/data/image/ImageCompressor.kt)
> 
> apk here -> [image-toolbox-2.3.2-jxl-arm64-v8a-release.zip](https://github.com/awxkee/jxl-coder/files/12545944/image-toolbox-2.3.2-jxl-arm64-v8a-release.zip)
> 
> fails with every image...

I'm sorry, partially it my mistake, effort must be clamped in 1..9.

Your lerp function is invalid. You have to use floats to make it working
`private fun IntRange.convert(
    number: Int,
    target: IntRange
): Int {
    val ratio = number.toFloat() / (endInclusive - start).toFloat()
    return (ratio * (target.last.toFloat() - target.first.toFloat())).roundToInt()
}`

**Comment by T8RIN** [comment]
1..9 without float values? And also that doesn't work even if i'm trying to use default 3 value

**Comment by awxkee** [comment]
> 1..9 without float values? And also that doesn't work even if i'm trying to use default 3 value

No, effort should be an integer.
Try to set directly 3 if should work.

You have to use floats in your interpolation function because it'll return just maximum all the time
`private fun IntRange.convert( number: Int, target: IntRange ): Int { val ratio = number.toFloat() / (endInclusive - start).toFloat() return (ratio * (target.last.toFloat() - target.first.toFloat())).roundToInt() }`

**Comment by T8RIN** [comment]
Oh, thanks, that's worked ! Can i use effort in lossless mode?

**Comment by awxkee** [comment]
> Oh, thanks, that's worked ! Can i use effort in lossless mode?

Yes, libjxl provides an option to set effort in lossless mode, but there is no any explanation will it work or won't

**Comment by T8RIN** [comment]
I've tried, it works perfectly
